version: '2'
services:
    jh01-app:
        image: jh01
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jh01-postgresql:5432/jh01
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jh01-elasticsearch:9300
        ports:
            - 8080:8080
    jh01-postgresql:
        extends:
            file: postgresql.yml
            service: jh01-postgresql
    jh01-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jh01-elasticsearch
